# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "courses", :force => true do |t|
    t.column "full_name",    :string,   :limit => 100, :default => "",   :null => false
    t.column "short_name",   :string,   :limit => 10,  :default => "",   :null => false
    t.column "description",  :text,                    :default => "",   :null => false
    t.column "started_at",   :datetime,                                  :null => false
    t.column "finished_at",  :datetime,                                  :null => false
    t.column "max_students", :integer,  :limit => 3,                     :null => false
    t.column "visible",      :boolean,                 :default => true, :null => false
  end

end
