# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "courses", :force => true do |t|
    t.column "full_name",    :string,   :limit => 100, :default => "",    :null => false
    t.column "short_name",   :string,   :limit => 10,  :default => "",    :null => false
    t.column "description",  :text
    t.column "started_at",   :datetime
    t.column "finished_at",  :datetime
    t.column "max_students", :integer
    t.column "visible",      :boolean,                 :default => false, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "username",         :string
    t.column "crypted_password", :string
    t.column "first_name",       :string
    t.column "last_name",        :string
    t.column "email",            :string
    t.column "description",      :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

end
